# Generated by Django 4.1.3 on 2022-11-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=250, verbose_name='Nome')),
                ('codigo_disciplina', models.CharField(max_length=250, verbose_name='Código')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('carga_horaria', models.DurationField(verbose_name='Carga Horaria')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curso.curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'ordering': ['nome_disciplina'],
            },
        ),
    ]
