# Generated by Django 4.1.3 on 2022-11-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.TimeField(verbose_name='Carga Horaria'),
        ),
    ]
