# Generated by Django 4.1.3 on 2022-11-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('disciplina', '0002_alter_disciplina_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
