# Generated by Django 4.1.3 on 2022-11-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professor.pessoa')),
                ('matricula', models.CharField(max_length=250, verbose_name='Matricula')),
                ('situacao', models.CharField(max_length=250, verbose_name='Situação')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curso.curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'ordering': ['nome'],
            },
            bases=('professor.pessoa',),
        ),
    ]
