# Generated by Django 4.1.3 on 2022-11-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=250, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professor.pessoa')),
                ('cod_professor', models.CharField(max_length=250, verbose_name='Codigo')),
                ('titulacaoMax', models.CharField(max_length=250, verbose_name='Titulação Máxima')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curso.curso')),
            ],
            options={
                'verbose_name': 'Professore',
                'ordering': ['nome'],
            },
            bases=('professor.pessoa',),
        ),
    ]
