# Generated by Django 4.1.3 on 2022-11-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('professor', '0001_initial'),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_turma', models.CharField(max_length=250, verbose_name='Codigo turma')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('dia_semana', models.IntegerField(verbose_name='Dia da semana')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disciplina.disciplina')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professor.professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'ordering': ['cod_turma'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(verbose_name='Nota 1')),
                ('nota2', models.FloatField(verbose_name='Nota 2')),
                ('provaFinal', models.FloatField(verbose_name='Prova final')),
                ('frequencia', models.IntegerField(verbose_name='Frequência')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.aluno')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='turma.turma')),
            ],
            options={
                'verbose_name': 'Avaliaçõe',
                'ordering': ['id_aluno'],
            },
        ),
    ]
