# Generated by Django 4.1.3 on 2022-11-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.IntegerField(verbose_name='Horario'),
        ),
    ]
